### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by alexeyr** [xixixao/Shem#1]
The README says

> I am providing code in this repository to you under an open source license.

but not what the license actually is (at least that I see).

**Comment by vyp** [comment]
https://github.com/xixixao/Shem/blob/eabac002261d8670763a1e6943841f7038295047/package.json#L22

**Comment by ghost** [comment]
@vyp that's not good enough.

The license has to be included with the code.

**Comment by xixixao** [comment]
Added LICENSE file. Let me know if that's not enough.
