### ISSUE TITLE
Grammar?

### ISSUE THREAD

**Issue by ghost** [xixixao/Shem#2]
Is the full grammar of the language posted somewhere? I'm trying to figure out the syntax and potentially make a parser for it. Thanks

**Comment by xixixao** [comment]
Nope, I don't have a formal grammar description. The basic syntax is just S-expressions with a couple of literals (strings, chars, regexes, this is not finalized). Then you have a set of builtins (like fn). Not sure how much detail you want your parser to distinguish. See tests and [my thesis](https://www.dropbox.com/s/02adjyvrsc4pdof/report.pdf?dl=0) for more examples.

Do let me know if you have more questions and if I can help.
