### ISSUE TITLE
is the idea you're taking the best of Clojure and Haskell?

### ISSUE THREAD

**Issue by faceyspacey** [xixixao/Shem#3]
I've been following the functional craze and in the middle of jumping ship from JS (React, Meteor, etc) to ClojureScript. I like Elm even better for the frontend, but I like the full stack opportunities CLJS provides. I stumbled on this, and with all the browser-based Bret Victor inspired goodness, it really seems up my alley--almost as if it solves as the problems I was searching for solutions for (minus all the libraries of a more mature ecosystem).

**Comment by xixixao** [comment]
Yes. Think of it as PureScript, with slightly different type system (no row types, implicit multi-parameter functional dependencies) using s-expressions to enable simple Clojure-style macros. There is a lot to be done here though, I cannot claim nowhere near the same maturity as PureScript, Elm or Clojure.
